### ISSUE TITLE
Display related publications/projects

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#20]
The client mentioned that Publications are always associated with Projects and asked if it would be possible for Projects to have a Publications field so that the Publications and PDF appear on the Project page. Not all Projects have Publications, but all Publications are associated with a Project. 

Also, could the Publications post type include a field to associate it with a Project?

**Comment by kpettinga** [comment]
@Jessdwilson I've added a field to publications that will let them select related projects. This one field can serve both publications and projects. In other words, one field to select related projects when editing publications will allow us to show related content on BOTH publications and projects.

I will work to make these related items appear on the frontend
