### ISSUE TITLE
Project option dates

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#21]
Projects always include a month and date in the Project Options field, is this required? The month and date don't appear on the front-end and the client only wants the years to appear, so is it necessary to add the month and date?
<img width="805" alt="screen shot 2017-05-24 at 10 53 02 am" src="https://cloud.githubusercontent.com/assets/1680051/26409794/95ccc3a0-406f-11e7-982e-fc7f779254bd.png">

**Comment by kpettinga** [comment]
@jessica, yes the in the backend you will be required to select a specify day. We can tweak it on the front end, however, to only show the year. I would suggest just picking Jan. 1st for the year they want.

**Comment by jessica-zzz** [comment]
oi
