### ISSUE TITLE
Team Page Partners and Supporters

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#23]
The client has a long list of [Partners and Supporters ](https://docs.google.com/spreadsheets/d/1RVlcRfFioj8B_mqT_rbq8ie2NPmazw7pq2E4BGQLb-c/edit#gid=1461570705) would it be possible to upload these as an Excel sheet to WordPress rather than enter individually under Team members?

**Comment by kpettinga** [comment]
@Jessdwilson yes, can they put it in a google spreadsheet for us? We can import it for them from there (b/c the process is a bit involved to import it correctly).

**Comment by Jessdwilson** [comment]
thanks @kpettinga I shared the Google doc with you of the Partners and Supporters to import, here is the link: https://docs.google.com/spreadsheets/d/1eAcEa4koGm746CYRKdBUDIf2OgqJ3axaQbXlnzpofwk/edit#gid=1229930931

**Comment by Jessdwilson** [comment]
also, the client requested: When you upload all the partners/supporters, can we make sure the partners category shows up after the board and before supporters

**Comment by kpettinga** [comment]
@Jessdwilson there's no indication in the spreadsheet of who is a "partner" and who is a "supporter". I will import them all as "partners" and it will be easy to bulk select and change the ones that should be "supporters" in wordpress.

**Comment by kpettinga** [comment]
also, most (if not all) of these partners/supporters should link out to their respective websites, no? If that's the case, we'll need their URLs. I could always just import them now without their URLs and they could be added later but in the meantime their links will go to empty an single team member page.

If we can get their URLs on that spreadsheet, I can just import them all in one swoop.

**Comment by Jessdwilson** [comment]
@kpettinga some of the partners and supporters that have been entered in WordPress are not appearing on the front-end, for example, AECOM, Asian American Federation, Alley Pond Environmental Center... 

also, can the partners and supporters be listed alphabetically by the first word in the name?

**Comment by kpettinga** [comment]
all set!
