### ISSUE TITLE
Projects hide services and issues

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#26]
From the client: 
I have a question about the backend, specifically about the services and issues. We are planning on adding some service areas to tag older projects, but they are not services we currently offer. In order to not mislead, is there a way to hide these from the filter list that shows up on the projects landing page?

**Comment by kpettinga** [comment]
@Jessdwilson 

If there are services/issues that are part of certain projects but the user shouldn't be able to filter by them, then they should not be included in the service/issue taxonomies at all.
So far, the only other use for assigning services/issues is that they get listed out on each project's page. I think the best solution would be to provide text boxes where they can write custom services/issues to be listed on individual project pages alongside the ones they selected in the taxonomy. Does that make sense?

Let's confirm with the client they would want to go this route before proceeding.

**Comment by Jessdwilson** [comment]
@kpettinga the client replied:

What we want to accommodate for are services that users should be able to filter by, but only by clicking on them from a project page. For example, we no longer do ‘design education’ programming, so we don’t want it to show up on the projects landing page as part of our menu of services. However, it would be nice to be able to click on ‘design education’ from the M.S. 131 project page, and then be taken to all the other design education projects. Is this possible? If it’s too round-about then having a text box for custom services will work!

**Comment by kpettinga** [comment]
@Jessdwilson 

Unfortunately that just doesn't work within the framework we have setup for project filtering. We can only filter by "visible" filters. Also, the filters themselves act as the indicator of which filters are selected/deselected. So, if we try to filter by a term that's not shown in the list, we would have to design a new way of displaying the current filter that doesn't rely on the filter name itself. 

The short story is that a text box for custom services/issues needs to be the way. I will set up the field.
