### ISSUE TITLE
Event day and time

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#29]
- [x] On events - we need to be able to specify an event end time. though the date does show up on the News page. When you go to the event itself they all say JAN. 1, 1970, 12:00AM
PS. 101 AUDITORIUM.
- [x] the date/location do not seem to be showing up on the published pages, 
<img width="799" alt="screen shot 2017-05-26 at 2 44 13 pm" src="https://cloud.githubusercontent.com/assets/1680051/26508223/e82f5d66-4221-11e7-90e8-f3e9f4154b6f.png">

**Comment by kpettinga** [comment]
~~**@Jessdwilson regarding event locations**:    
are events supposed to have a map associated with them? I did not see one in the original design spec. The location is only shown as text in the spec.~~

**Comment by kpettinga** [comment]
Nevermind! I saw that the location was displaying hardcoded text and not the actual text field content.
