### ISSUE TITLE
Blockquotes text size adjustment

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#33]
With the blockquotes, would it be possible to have an option to adjust the text size?
We noticed on the About page the quote size appears too large (screenshot attached) We'd like to be able to adjust the size so we can distinguish the quote's position/org and make sure they don't overpower the page when we have longer quotes.
<img width="1299" alt="screen shot 2017-05-26 at 3 13 57 pm" src="https://cloud.githubusercontent.com/assets/1680051/26509250/fa2b244c-4225-11e7-8bdc-26855d8a8c15.png">

**Comment by Jessdwilson** [comment]
@kpettinga how do we adjust the quotes? If I change the heading size for the quote on the About page nothing changes on the front-end. They want the quote and byline to be different sizes to distinguish the two
<img width="826" alt="screen shot 2017-05-30 at 10 38 27 am" src="https://cloud.githubusercontent.com/assets/1680051/26589035/eb57f2a4-4524-11e7-91da-8323a1f2f66a.png">

**Comment by kpettinga** [comment]
CACHE CACHE CACHE!

always clear your cache :)
