### ISSUE TITLE
Disappeared elements from pages 

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/Hester-Street#34]
Using the up-to-date chrome loads of elements are "there" but not visible.

- [ ] Logo on all pages
- [ ] Map on project page
- [x] Hamburger on pages (home mostly)
- [ ] Close icon on navigation take-over
- ~~Tagline on nav take-over~~ 

Screen shots to show you what I'm witnessing.

![screen shot 2017-05-26 at 3 19 56 pm](https://cloud.githubusercontent.com/assets/12611145/26509454/d64707fc-4226-11e7-95ad-8687f4a3d1e9.png)

![screen shot 2017-05-26 at 3 20 38 pm](https://cloud.githubusercontent.com/assets/12611145/26509469/e3d257a0-4226-11e7-8b91-2d0efa44bf9b.png)

![screen shot 2017-05-26 at 3 21 01 pm](https://cloud.githubusercontent.com/assets/12611145/26509481/ef9a781a-4226-11e7-9182-ce8f28d131ec.png)

**Comment by kpettinga** [comment]
@elliotarthur 

I'm not able to replicate these issues. can you confirm with the rest of the team to see if it's happening for them? Please clear your cache and load pages with the inspector open.

If you see something broken, can you screenshot any errors you see in the (inspector) console?

> tagline on takeover

@jalbertgagnier requested this be removed in the takeover nav

**Comment by elliotarthur** [comment]
@kpettinga I cleared cache and refreshed multiple times. Will see if anyone else can replicate this issue.

Re: Tagline Takeover. Can the vertical lines go full height of the browser still?
