### ISSUE TITLE
Navigation take-over

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/Hester-Street#35]
- [x] I'm noticing (again in chrome) a slight nudge to the left with the navigation. It's not perfectly aligning with the elements of the page it's taking over.

-  [x] Also, there's a long delay with the color transition from the color to black. It's not as quick as it shows from color to color.

**Comment by kpettinga** [comment]
@elliotarthur i don't see the nudge you're talking about... are you seeing this on a specific page?

fixed the color transition delay.
