### ISSUE TITLE
Safari homepage publications secondary image

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#39]
In Safari the secondary featured image is stacked above the Publication image instead of appearing to the left of the rule line
<img width="712" alt="screen shot 2017-05-30 at 11 54 22 am" src="https://cloud.githubusercontent.com/assets/1680051/26592648/5a81341a-452f-11e7-8953-f21e925bd52e.png">

**Comment by kpettinga** [comment]
should be fixed now
