### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/Hester-Street#42]
![favicon](https://cloud.githubusercontent.com/assets/12611145/26644742/ca569c92-4603-11e7-85f6-19662475a722.png)

**Comment by elliotarthur** [comment]
it's 32x32. That's ok for retina right?

**Comment by kpettinga** [comment]
Hey @elliotarthur these can actually be uploaded right in wordpress now! They need to be 512x512 though. I'll go ahead and scale it up
