### ISSUE TITLE
Stripe email notification

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#46]
see email from Lori, possible for recipients to receive a single email like the test email from Stripe attached?
<img width="878" alt="screen shot 2017-06-01 at 12 35 17 pm" src="https://cloud.githubusercontent.com/assets/1680051/26690334/e5d419d6-46c6-11e7-9631-b27b278d8edb.png">

**Comment by kpettinga** [comment]
@Jessdwilson all set. I responded to the email.

We'll let Stripe handle email notification and the form on the website, once submitted, will display a confirmation message.
