### ISSUE TITLE
Improve SEO 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#48]
when searching for Hester Street it appears as the 4th search result, possible to improve?
<img width="703" alt="screen shot 2017-06-01 at 6 01 32 pm" src="https://cloud.githubusercontent.com/assets/1680051/26702760/7935ed6c-46f4-11e7-9673-cf9a458dd50d.png">

**Comment by kpettinga** [comment]
@Jessdwilson 

First off, there's no quick fix to improving your google rankings. It is a factor of a multitude of things, some of which we can control, others we can't. The Hester Street film, for instance, is more ubiquitous and therefore more likely to be what a user is looking for, hence, it shows up first.

Here's a list of things that we DO have control over which can improve rankings:

**For the webmaster**
- Install the Yoast SEO plugin. This will allow you to configure SEO settings for the site and every page and post - _completed_
- Secure your site with an SSL certificate - _completed_
- Optimize site performance - _completed_
- Configure site visibility settings - _completed_
- Using SEO friendly URL structure in WordPress - _completed_
- Use the `rel="nofollow"` attribute on external links - _completed_
- Only show a post's full text if on that post's page. Everywhere else, use an excerpt. This helps Google know that you don't have duplicate pages - _completed_
- Install security plugin. Sites compromised by hackers are blacklisted from Google. We've installed a plugin to manage the security of your site - _completed_

**For those entering content**
- Provide internal links wherever possible. For instance, whenever you mention "contact us", make sure to provide a link to the Contact page.
- Optimize images - Make sure to provide succinct and descriptive text for the "Title" and "Alt" fields for each image. Google reads this information as well as screen readers for the visually impaired. As well, you can take steps to compressing your image's size. This happens before you import the image into wordpress. [See this article about optimizing images for web](http://www.wpbeginner.com/beginners-guide/speed-wordpress-save-images-optimized-web/)
- Check the Yoast SEO settings for each page/post.

**Action Needed:**
- Please go to https://hesterstreet.org/wp-admin/admin.php?page=wpseo_search_console&tab=settings and click the "Get Google Authorization Code" button. Once you have the code, enter it into the text box and click "Authenticate".

See this page for a complete rundown of improving SEO on Wordpress sites:    
http://www.wpbeginner.com/wordpress-seo/

**Comment by Jessdwilson** [comment]
thanks! this is helpful
