### ISSUE TITLE
Project page loading

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#50]
When first loading the project landing page the attached always appears. Is this possible to avoid? 
I see this in Chrome and Safari

<img width="837" alt="screen shot 2017-06-05 at 12 54 58 pm" src="https://cloud.githubusercontent.com/assets/1680051/26794073/4a5fcd30-49ee-11e7-96b2-c4283c62a2a2.png">

**Comment by kpettinga** [comment]
this should be fixed
