### ISSUE TITLE
Homepage add navigation to hamburger menu

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#56]
> can we make the strapline + featured post show up even before the menu? So that when you get to the home page the first thing you see is the strapline + featured post alongside the hamburger, and only see the whole menu as a takeover?

**Comment by kpettinga** [comment]
@Jessdwilson did @travis and @jalbertgagnier approve this?

**Comment by jalbertgagnier** [comment]
I talked about it with Travis and we think this is what was intended all along. Good to go.

**Comment by kpettinga** [comment]
@Jessdwilson This is all set
