### ISSUE TITLE
Project landing page no projects 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#57]
@kpettinga when visiting the Projects landing page the following message appears 
<img width="1275" alt="screen shot 2017-06-13 at 12 43 29 pm" src="https://user-images.githubusercontent.com/1680051/27093814-0eeae0e8-5036-11e7-900a-33051847fe91.png">

**Comment by kpettinga** [comment]
Thanks @Jessdwilson this should be fixed
