### ISSUE TITLE
Newsletter links

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#58]
From client:
Is there a way to edit this post type so that we can insert the mailchimp link (below), and then when you’re on the news landing page, the newsletter preview links directly to it? Or embed the newsletter in the post? Basically we just want to minimize the number of links you have to get through to see the newsletter, so that you’re clicking news page > newsletter rather than news page > newsletter preview > newsletter.
http://mailchi.mp/a7d4a766cbe4/hester-street-template-test-163311

KP: We will need to setup a new custom field so they can enter a link to each newsletter. We can make the preview on the news page link directly to it.

**Comment by Jessdwilson** [comment]
@kpettinga to confirm, would they enter the link into the External URL under Post Options?

<img width="858" alt="screen shot 2017-07-05 at 11 02 14 am" src="https://user-images.githubusercontent.com/1680051/27870673-81855114-6171-11e7-9503-9c7c85c68c6c.png">

**Comment by Jessdwilson** [comment]
@kpettinga Anna entered the url under external url for the "June at Hester Street" post: http://hesterstreet.org/2017/06/june-at-hester-street/

But it doesn't redirect to the newsletter from the news page, is there something more they need to do?

**Comment by kpettinga** [comment]
Hey Jessica, the code needed to be pushed live. Should be fixed.
