### ISSUE TITLE
GeoJson files

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#59]
From Client:
Rehanna at our office has been trying to upload GeoJson files and is running into some issues with file size. I’m pasting the message from her below, is there a way to increase the maximum upload size?
 
“GeoJson file converted to text for New York City boundaries is 2.8 mb, and when I try to upload it, there’s a max file size of 2.5 mb. I tried searching to see if the .txt file could be compressed, but the only way I found was by putting it in a zip, but then it won’t upload that way.”

**Comment by kpettinga** [comment]
@Jessdwilson 
I've checked on this and the site has a max file size of 50 mb. See screenshot below:
![image](https://user-images.githubusercontent.com/1746410/27865981-a5750204-6162-11e7-8ed9-9e5bcc77897d.png)

I successfully uploaded a txt file that was 3.1 mb. Please have the client double check that their file is less than 50mb. If they're having trouble, have them send us the file they're trying to upload.

**Comment by Jessdwilson** [comment]
@kpettinga from Anna: I think we found the real issue - we are able to upload bigger files through the media library (though not through the field on project pages), but when we try to select files in the map field we get an error message, see screenshot attached. I’m also including the GeoJson txt file and zipped shapefile for reference.

![restricted upload nybb](https://user-images.githubusercontent.com/1680051/27932823-255f573e-626d-11e7-8d2b-e991e843c771.PNG)
[NYBB_GeoJson.txt](https://github.com/ObjectiveSubject/Hester-Street/files/1129282/NYBB_GeoJson.txt)
[nybb.zip](https://github.com/ObjectiveSubject/Hester-Street/files/1129284/nybb.zip)

**Comment by kpettinga** [comment]
@Jessdwilson 

I just upgraded the limit to match that of the rest of the media library, 50mb. Please note that uploading geoJSON .txt files larger than 5-10mb is likely to cause performance issues where that data is displayed. Just something to be aware of.
