### ISSUE TITLE
Publications landing page full opacity

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#62]
From Client: 
Can it be adjusted so that all the thumbnails show up at full opacity? If the text still changes color on hover that seems like enough of an indication of where you’re at

**Comment by Jessdwilson** [comment]
@kpettinga I cleared my browser cache but the publication images and text _are not_ appearing at full opacity like the first publication post

**Comment by kpettinga** [comment]
@Jessdwilson haven't pushed the code yet. Just marking these off as I go. Check back in an hour or so and it should be fixed.
