### ISSUE TITLE
install Premium EV SSL certificate

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#64]
from Anna: It looks like our Premium EV SSL certificate has now been fully processed, see email below. Is it possible for you to install this?

Congratulations on becoming an SSL certificate owner for the domain: hesterstreet.org! We're delighted to have you on board. 

What's Next? 

1. Download your certificate, by logging in to your account at https://certs.godaddy.com/home.pki?AccountUid=804f4d4d-3fd0-11e7-80e2-3417ebe72595.
2. [Click here](https://www.godaddy.com/help/install-ssl-certificates-16623) to follow our easy instructions to install your certificate.

**Comment by kpettinga** [comment]
@Jessdwilson this is all set. new SSL cert is installed.
