### ISSUE TITLE
project maps

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#69]
I noticed a small issue with a few of the project maps. On the projects linked below, I can’t edit the maps - I’m not sure how we added those polygons in the first place (there are no geojson txt files for them in our media library) but no matter how many times I try to delete the shapes/points they keep showing up. Is it possible for you to look into this and clear those maps for us?
 
https://hesterstreet.org/projects/brighton-beach/
https://hesterstreet.org/projects/les-ready/
https://hesterstreet.org/projects/people-make-parks/

**Comment by kpettinga** [comment]
@Jessdwilson this should be all set. There was a glitch with those particular projects because they were originally imported from our local development server. I've recreated the posts and cleared all the data on the maps. Once new data is added, the maps will show up again on the front-end.
