### ISSUE TITLE
Site updates

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/Hester-Street#70]
From Anna:

**Project timeline edits:**

- [x] Remove timeline filters - we are not adding enough timeline items for filter to be necessary

- [x] Not sure if this is an error but the entire timeline shows up grayed out, can we make it full opacity?

- [x] Change date field so front end only shows month and year, and make it possible to show a range instead of a single date

- [x] Change the scroll so that stage label and content scroll together, or stage label is highlighted when you get to corresponding content. With everything grayed out it can be hard to tell which labels match which content.
 
For reference, here are 2 projects we’ve been testing the timeline out on:
http://hesterstreet.org/projects/lower-manhattan-coastal-resiliency-project/
http://hesterstreet.org/projects/createnyc/

Also, a troubleshooting question:

- [x] We are interested in adding some collaborators to our Team page. We built this feature in previously, but I think we asked to have it turned off so that ‘Collaborators’ and ‘Alumni’ don’t show up on the team page. Is it possible to give us the ability to turn them on and off? If that is too time-consuming let's just make collaborators visible

- [x] On the home page, I think the most recent 3 posts are supposed to show up under “News,” but these don’t update automatically and there is no option to change them on the home page back-end. Can you look into this?

**Comment by kpettinga** [comment]
Hey @Jessdwilson I think 2 days is still a good estimate here. For Team page stuff, will only need an additional 1 or 2 max so it can probably be lumped into the 2 day estimate.

**Comment by kpettinga** [comment]
@Jessdwilson 

> We are interested in adding some collaborators to our Team page. We built this feature in previously, but I think we asked to have it turned off so that ‘Collaborators’ and ‘Alumni’ don’t show up on the team page. Is it possible to give us the ability to turn them on and off? If that is too time-consuming let's just make collaborators visible

I've added some fields to the Team page so the client can select which roles appear and in what order. You can also select how they appear, either as a profile card (with or without image) or just regular text. I've setup the roles as they were before, now they just need to add Collaborators and Alumni whenever they wish. Drag the numbers to the left of each row to reorder roles.

**Comment by kpettinga** [comment]
@Jessdwilson 

>Change the scroll so that stage label and content scroll together, or stage label is highlighted when you get to corresponding content. With everything grayed out it can be hard to tell which labels match which content.

I've refactored this part so that each timeline item label and date begins where their respective content is. As you scroll, the label and date will follow for the length of the content. Since we removed the opacity and are no longer using that as a highlighting mechanism, this new method acts well to properly orient users as to which labels/dates belong to which content blocks.

**Comment by Jessdwilson** [comment]
from client:

I just have one question about the collaborators - is it possible to make it so they automatically show up alphabetical by last name like the staff and board?

**Comment by kpettinga** [comment]
@Jessdwilson I've implemented a new field where they can select the way in which team members get organized for each section. I've applied "Last Name" for the applicable sections.

![image](https://user-images.githubusercontent.com/1746410/39115862-42510bd4-46e3-11e8-855c-387797f849c1.png)
